<?php
$routes = [
    'metadata',
    'getAccessToken',
    'refreshToken',
    'revokeAccessToken',
    'getMe',
    'getStartPageToken',
    'getChanges',
    'subscribeToUserChanges',
    'stopWatchingChannelResources',
    'createFileComment', // 1
    'deleteFileComment',
    'getFileSingleComment',
    'getFileComments',
    'updateFileComment',
    'copyFile',
    'createFileFromUpload',
    'updateFileFromUpload',
    'updateFileFromMultipartData',
    'updateFileFromMetadata',
    'createFileFromMetadata',
    'createFileFromMultipartData',
    'deleteFile',
    'emptyTrash',
    'exportFile',
    'generateFileIds',
    'getSingleFile',
    'getFiles',
    'updateMultipartFile',
    'subscribeToFileChanges',
    'createFilePermission',
    'deleteFilePermission',
    'getFileSinglePermission',
    'getFilePermissions',
    'updateFilePermission',
    'createReplyToComment',
    'deleteCommentReply',
    'getSingleReply',
    'getCommentReplies',
    'updateCommentReply',
    'deleteFileRevision',
    'getFileSingleRevision',
    'getFileRevisions',
    'updateFileRevision',
    'createTeamDrive',
    'deleteTeamDrive',
    'getSingleTeamDrive',
    'getTeamDrives',
    'updateTeamDrive'
];
foreach($routes as $file) {
    require __DIR__ . '/../src/routes/'.$file.'.php';
}

